"""add track_id to students

Revision ID: 99f41eca3031
Revises: b0f3457f648c
Create Date: 2023-10-21 12:34:14.025702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99f41eca3031'
down_revision = 'b0f3457f648c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dept_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'tracks', ['dept_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('dept_id')

    # ### end Alembic commands ###
